version: "3.9"
services:
  app:
    container_name: CurrencyServiceApplication
    command: java -jar target/CurrencyServiceApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8084:8084
    expose:
      - 8084
    volumes:
      - ./:/app/app
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    name: KBE
    external: true


