version: "3.9"
services:
  app:
    container_name: CurrencyServiceApplication
    command: java -jar target/CurrencyServiceApplication-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - 8082:8082
    expose:
      - 8082
    volumes:
      - ./:/app/app



